name: Tests

on:
  push:
    branches:
      - main
  create:
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    # Run every day at 7:42am UTC.
    - cron:  '42 7 * * *'

jobs:
  test-benchmark:
    uses: benchopt/benchopt/.github/workflows/test_benchmark.yml@MTN_reusable_workflow
    with:
      benchopt_branch: benchopt:MTN_reusable_workflow

